excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://ksspikes.github.io
title: Awesome
email: me@koreyspikes.com
author: Korey Spikes
description: My awesome new site
paginate: 5
google_analytics: 